backend:
  name: github
  repo: nickc5115/jakedillon
  branch: main
  base_url: https://jakedillonmusic-cms-oauth.onrender.com
  auth_endpoint: /auth

media_folder: "resources/images/gallery"
public_folder: "/resources/images/gallery"

collections:
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Description", name: "body", widget: "text", required: false }